package com.megapelis.service.model.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.megapelis.service.util.MovieSerieConstant;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = MovieSerieConstant.TABLE_MOVIE_SERIE_NAME)
public class MovieSerie {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute(attributeName = "id_tmdb")
    private String idTMDB;

    @DynamoDBAttribute(attributeName = "premiere_date")
    private String premiereDate;

    @DynamoDBAttribute
    private String image;

    @DynamoDBAttribute
    private String points;

    @DynamoDBAttribute
    private String genders;

    @DynamoDBAttribute(attributeName = "created_date")
    private String createdDate;

    @DynamoDBAttribute(attributeName = "last_modified_date")
    private String lastModifiedDate;

    @DynamoDBAttribute
    private String status;
}
