package com.megapelis.service.model.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.megapelis.service.util.MovieSerieConstant;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = MovieSerieConstant.TABLE_MOVIE_SERIE_NAME)
public class MovieSerie {

    @DynamoDBHashKey(attributeName = MovieSerieConstant.TABLE_MOVIE_SERIE_COLUMN_ID)
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = MovieSerieConstant.TABLE_MOVIE_SERIE_COLUMN_NAME)
    private String name;

    @DynamoDBAttribute(attributeName = MovieSerieConstant.TABLE_MOVIE_SERIE_COLUMN_ID_TMDB)
    private String idTMDB;

    @DynamoDBAttribute(attributeName = MovieSerieConstant.TABLE_MOVIE_SERIE_COLUMN_IMAGE)
    private String image;

    @DynamoDBAttribute(attributeName = MovieSerieConstant.TABLE_MOVIE_SERIE_COLUMN_POINTS)
    private String points;

    @DynamoDBAttribute(attributeName = MovieSerieConstant.TABLE_MOVIE_SERIE_COLUMN_STATUS)
    private String status;

    @DynamoDBAttribute(attributeName = MovieSerieConstant.TABLE_MOVIE_SERIE_COLUMN_TYPE_SERVICE)
    private String typeService;

    @DynamoDBAttribute(attributeName = MovieSerieConstant.TABLE_MOVIE_SERIE_COLUMN_PREMIERE_DATE)
    private String premiereDate;

    @DynamoDBAttribute(attributeName = MovieSerieConstant.TABLE_MOVIE_SERIE_COLUMN_CREATED_DATE)
    private String createdDate;

    @DynamoDBAttribute(attributeName = MovieSerieConstant.TABLE_MOVIE_SERIE_COLUMN_LAST_MODIFIED_DATE)
    private String lastModifiedDate;
}
